version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update: "semver-major"
    groups:
      security-patch-minor:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
